name: API Tests with Newman

on:
  push:
    branches: [main]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create Laravel .env file
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          envsubst < sprint5-with-bugs/API/.env.ci > sprint5-with-bugs/API/.env

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Wait for Services
        run: sleep 60

      - name: Setup Application
        run: |
          docker compose run --rm composer
          docker compose exec -T -u root laravel-api \
            chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
          docker compose exec -T laravel-api php artisan migrate:fresh --seed --force

      - name: Run tests with Newman
        working-directory: sprint5-with-bugs/tests
        run: |
          newman run sprint5-with-bugs/tests/api/Authentication.postman_collection.json \
            --iteration-data sprint5-with-bugs/tests/api/data.csv \
            --reporters cli

      - name: Show API logs on failure
        if: failure()
        run: |
          export SPRINT=sprint5-with-bugs
          export DISABLE_LOGGING=true
          echo "=== API Logs ==="
          docker compose logs laravel-api || true
          echo "=== Database Logs ==="
          docker compose logs mariadb || true

      - name: Clean up
        if: always()
        run: |
          export SPRINT=sprint5-with-bugs
          export DISABLE_LOGGING=true
          docker compose down -v || true
