name: API Tests with Newman

on:
  push:
    branches: [main]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start all services
        run: |
          export SPRINT=sprint5-with-bugs
          export DISABLE_LOGGING=true
          docker compose up -d

      - name: Wait for services to be ready
        run: |
          # Wait for MariaDB to be ready
          echo "Waiting for MariaDB to be ready..."
          timeout 60 bash -c 'until docker compose exec -T mariadb mysqladmin ping -h localhost --silent; do sleep 2; done'

      - name: Initialize database
        run: |
          export SPRINT=sprint5-with-bugs
          export DISABLE_LOGGING=true
          ./init-data.sh

      - name: Run Login tests with Newman
        working-directory: sprint5-with-bugs/tests
        run: |
          newman run Authentication.postman_collection.json \
            --iteration-data data.csv \
            --reporters cli

      - name: Show API logs on failure
        if: failure()
        run: |
          export SPRINT=sprint5-with-bugs
          export DISABLE_LOGGING=true
          echo "=== API Logs ==="
          docker compose logs laravel-api || true
          echo "=== Database Logs ==="
          docker compose logs mariadb || true

      - name: Clean up
        if: always()
        run: |
          export SPRINT=sprint5-with-bugs
          export DISABLE_LOGGING=true
          docker compose down -v || true
